[package]
authors = ["Sebastien Rousseau <sebastian.rousseau@gmail.com>"]
build = "build.rs"
categories = [
    "algorithms",
    "authentication",
    "cryptography",
    "data-structures",
    "encoding",
]
description = "Quantum-Resistant Cryptographic Hash Library for Password Encryption and Verification in Rust"
documentation = "https://docs.rs/hsh"
edition = "2021"
exclude = ["/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"]
homepage = "https://minifunctions.com/"
keywords = ["argon2", "argon2i", "hash", "password", "security"]
license = "MIT OR Apache-2.0"
name = "hsh"
repository = "https://github.com/sebastienrousseau/hsh/"
rust-version = "1.69.0"
version = "0.0.6"
include = [
    "/CONTRIBUTING.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/examples/**",
    "/README.md",
    "/src/**",
    "/tests/**",
    "/xtask/**",
]

[workspace]
members = ["xtask"]

[[bench]]
name = "benchmark"
harness = false
path = "benches/criterion.rs"

[profile.bench]
debug = true

[[example]]
name = "hsh"
path = "examples/hsh.rs"

[dependencies]
argon2rs = "0.2.5"
base64 = "0.21.4"
bcrypt = "0.15.0"
dtt = "0.0.4"
log = {version="0.4.20", features = ["std"] }
openssl = { version = "0.10.57", features = ["vendored"] }
scrypt = "0.11.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
vrd = "0.0.4"

[dev-dependencies]
assert_cmd = "2.0.12"
criterion = "0.5.1"

[lib]
crate-type = ["lib"]
name = "hsh"
path = "src/lib.rs"

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1        # Compile crates one after another so the compiler can optimize better
debug = false            # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false      # Disable incremental compilation
lto = true               # Enables link to optimizations
opt-level = "s"          # Optimize for binary size
overflow-checks = false  # Disable overflow checks
panic = "abort"          # Strip expensive panic clean-up logic
rpath = false            # Disable rpath
strip = "symbols"        # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
