#![allow(missing_docs)]
#![allow(clippy::unwrap_used, clippy::expect_used)]
// Copyright © 2023-2026 Hash (HSH) library contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Property tests for `hsh-digest`.
//!
//! These are mathematical invariants that must hold for any input the
//! parser / hasher accepts. The corpus is generated by `proptest` —
//! 256 cases per property (the default) per CI run, multiplied across
//! algorithm variants.

use hsh_digest::{hash, Algorithm, Hasher};
use proptest::prelude::*;

// ---------------------------------------------------------------------------
// One-shot vs. streaming equivalence
//
// `hash(alg, &bytes)` MUST equal `Hasher::new(alg).update(bytes).finalize()`
// for every input. If they ever differ, one of the two paths has a bug.
// ---------------------------------------------------------------------------

proptest! {
    #[cfg(feature = "sha2")]
    #[test]
    fn one_shot_eq_streaming_sha256(input in proptest::collection::vec(any::<u8>(), 0..4096)) {
        let one = hash(Algorithm::Sha256, &input).unwrap();
        let mut streaming = Hasher::new(Algorithm::Sha256).unwrap();
        streaming.update(&input);
        let stream = streaming.finalize();
        prop_assert_eq!(one, stream);
    }

    #[cfg(feature = "sha2")]
    #[test]
    fn one_shot_eq_streaming_sha512(input in proptest::collection::vec(any::<u8>(), 0..4096)) {
        let one = hash(Algorithm::Sha512, &input).unwrap();
        let mut streaming = Hasher::new(Algorithm::Sha512).unwrap();
        streaming.update(&input);
        let stream = streaming.finalize();
        prop_assert_eq!(one, stream);
    }

    #[cfg(feature = "sha3")]
    #[test]
    fn one_shot_eq_streaming_sha3_256(input in proptest::collection::vec(any::<u8>(), 0..4096)) {
        let one = hash(Algorithm::Sha3_256, &input).unwrap();
        let mut streaming = Hasher::new(Algorithm::Sha3_256).unwrap();
        streaming.update(&input);
        let stream = streaming.finalize();
        prop_assert_eq!(one, stream);
    }

    #[cfg(feature = "blake3")]
    #[test]
    fn one_shot_eq_streaming_blake3(input in proptest::collection::vec(any::<u8>(), 0..4096)) {
        let one = hash(Algorithm::Blake3, &input).unwrap();
        let mut streaming = Hasher::new(Algorithm::Blake3).unwrap();
        streaming.update(&input);
        let stream = streaming.finalize();
        prop_assert_eq!(one, stream);
    }
}

// ---------------------------------------------------------------------------
// Chunking equivalence
//
// Hashing N bytes in one update MUST equal hashing them in K arbitrarily-
// sized chunks. This is the *defining* property of an incremental hash.
// If a SIMD path mishandles a partial block boundary, this catches it.
// ---------------------------------------------------------------------------

proptest! {
    #[cfg(feature = "sha2")]
    #[test]
    fn chunking_equivalence_sha256(
        input  in proptest::collection::vec(any::<u8>(), 1..2048),
        splits in proptest::collection::vec(0usize..=2048, 0..16),
    ) {
        let baseline = hash(Algorithm::Sha256, &input).unwrap();
        let mut h = Hasher::new(Algorithm::Sha256).unwrap();
        let mut cursor = 0;
        for split in &splits {
            let end = (cursor + split).min(input.len());
            h.update(&input[cursor..end]);
            cursor = end;
        }
        h.update(&input[cursor..]);
        prop_assert_eq!(baseline, h.finalize());
    }

    #[cfg(feature = "blake3")]
    #[test]
    fn chunking_equivalence_blake3(
        input  in proptest::collection::vec(any::<u8>(), 1..2048),
        splits in proptest::collection::vec(0usize..=2048, 0..16),
    ) {
        let baseline = hash(Algorithm::Blake3, &input).unwrap();
        let mut h = Hasher::new(Algorithm::Blake3).unwrap();
        let mut cursor = 0;
        for split in &splits {
            let end = (cursor + split).min(input.len());
            h.update(&input[cursor..end]);
            cursor = end;
        }
        h.update(&input[cursor..]);
        prop_assert_eq!(baseline, h.finalize());
    }
}

// ---------------------------------------------------------------------------
// Output-length invariant
//
// Every supported algorithm has a fixed-width output. The hasher must
// produce exactly that many bytes regardless of input length / content.
// ---------------------------------------------------------------------------

#[cfg(feature = "sha2")]
const SHA256_LEN: usize = 32;
#[cfg(feature = "sha2")]
const SHA384_LEN: usize = 48;
#[cfg(feature = "sha2")]
const SHA512_LEN: usize = 64;
#[cfg(feature = "blake3")]
const BLAKE3_LEN: usize = 32;

proptest! {
    #[cfg(feature = "sha2")]
    #[test]
    fn output_length_fixed(input in proptest::collection::vec(any::<u8>(), 0..1024)) {
        prop_assert_eq!(hash(Algorithm::Sha256, &input).unwrap().len(), SHA256_LEN);
        prop_assert_eq!(hash(Algorithm::Sha384, &input).unwrap().len(), SHA384_LEN);
        prop_assert_eq!(hash(Algorithm::Sha512, &input).unwrap().len(), SHA512_LEN);
    }

    #[cfg(feature = "blake3")]
    #[test]
    fn output_length_blake3(input in proptest::collection::vec(any::<u8>(), 0..1024)) {
        prop_assert_eq!(hash(Algorithm::Blake3, &input).unwrap().len(), BLAKE3_LEN);
    }
}

// ---------------------------------------------------------------------------
// Determinism
//
// Same input + same algorithm MUST always produce the same digest.
// Catches accidental randomness leaks (e.g. an internal state init
// reading from /dev/urandom).
// ---------------------------------------------------------------------------

proptest! {
    #[cfg(feature = "sha2")]
    #[test]
    fn determinism_sha256(input in proptest::collection::vec(any::<u8>(), 0..2048)) {
        let a = hash(Algorithm::Sha256, &input).unwrap();
        let b = hash(Algorithm::Sha256, &input).unwrap();
        prop_assert_eq!(a, b);
    }
}

// ---------------------------------------------------------------------------
// Cross-algorithm distinctness (collision-resistance smoke)
//
// Same input under two different algorithms MUST produce different
// digests (modulo astronomically rare collisions that this corpus
// cannot hit). Catches "we wired SHA-384 to call SHA-512" copy-paste
// bugs.
// ---------------------------------------------------------------------------

proptest! {
    #[cfg(all(feature = "sha2", feature = "sha3"))]
    #[test]
    fn sha2_neq_sha3(input in proptest::collection::vec(any::<u8>(), 1..1024)) {
        let a = hash(Algorithm::Sha256,  &input).unwrap();
        let b = hash(Algorithm::Sha3_256, &input).unwrap();
        // Both are 32 bytes but different families — must differ.
        prop_assert_ne!(a, b);
    }

    #[cfg(all(feature = "sha2", feature = "blake3"))]
    #[test]
    fn sha2_neq_blake3(input in proptest::collection::vec(any::<u8>(), 1..1024)) {
        let a = hash(Algorithm::Sha256, &input).unwrap();
        let b = hash(Algorithm::Blake3, &input).unwrap();
        prop_assert_ne!(a, b);
    }
}
