name: 🧪 Check

on:
  push:
    branches:
      - feat/hsh
  pull_request:
    branches:
      - feat/hsh
  release:
    types: [created]

jobs:
  all:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
      - uses: actions/checkout@v4
      - name: Check lints
        run: cargo check --all-targets --workspace --all-features